# Generated by Django 5.0.2 on 2024-02-16 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 57, 18, 992414, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
