# Generated by Django 5.0.2 on 2024-02-16 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_news_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsphoto',
            old_name='news',
            new_name='news_reference',
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 15, 36, 9, 859048, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
