# Generated by Django 5.0.2 on 2024-02-16 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_news_newsphoto_news_reference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 16, 29, 21, 151793, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
