# Generated by Django 5.0.2 on 2024-02-17 03:33

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 3, 33, 39, 19848, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='newsphoto',
            name='news_reference',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_reference', to='api.news'),
        ),
    ]
