# Generated by Django 5.0.2 on 2024-02-17 06:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('has_sub_section', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 6, 47, 2, 646995, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='SubHeaders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('referece_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers_ref', to='api.headers')),
            ],
        ),
    ]
