# Generated by Django 5.0.2 on 2024-02-17 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 6, 51, 2, 156320, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
