# Generated by Django 5.0.2 on 2024-02-17 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('Bangladesh & Politics', 'Bangladesh & Politics'), ('Bangladesh & economics', 'Bangladesh & economics'), ('Bangladesh & report', 'Bangladesh & report'), ('National', 'National'), ('International', 'International'), ('Sports & Cricket', 'Sports & Cricket'), ('Sports & Football', 'Sports & Football'), ('Jobs', 'Jobs')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 14, 29, 45, 799451, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
