# Generated by Django 5.0.2 on 2024-02-18 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_news_news_category_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='read_times',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 16, 7, 59, 936398, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('bangladesh & politics', 'Bangladesh & politics'), ('bangladesh & economics', 'Bangladesh & economics'), ('bangladesh & report', 'Bangladesh & report'), ('national', 'National'), ('international', 'International'), ('sports & cricket', 'Sports & cricket'), ('sports & football', 'Sports & football'), ('jobs', 'Jobs')], max_length=100, null=True),
        ),
    ]
