# Generated by Django 5.0.2 on 2024-02-21 06:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_advertisement_alter_news_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.news')),
                ('speaker', models.CharField(max_length=50)),
            ],
            bases=('api.news',),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 6, 32, 30, 289568, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
