# Generated by Django 5.0.2 on 2024-02-21 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_opinion_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 21, 6, 33, 14, 860541, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
