# Generated by Django 5.0.2 on 2024-03-08 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 8, 13, 35, 29, 437421, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('bangladesh & politics', 'Bangladesh & politics'), ('bangladesh & economics', 'Bangladesh & economics'), ('bangladesh & report', 'Bangladesh & report'), ('national', 'National'), ('international', 'International'), ('sports & cricket', 'Sports & cricket'), ('sports & football', 'Sports & football'), ('opinions', 'Opinions'), ('jobs', 'Jobs')], max_length=100, null=True),
        ),
    ]
