# Generated by Django 5.0.2 on 2024-04-05 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publishing_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 8, 18, 20, 44904, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_category',
            field=models.CharField(choices=[('bangladesh & politics', 'Bangladesh & politics'), ('angladesh & economics', 'Bangladesh & economics'), ('bangladesh & report', 'Bangladesh & report'), ('national', 'National'), ('international', 'International'), ('sports & cricket', 'Sports & cricket'), ('sports & football', 'Sports & football'), ('opinions', 'Opinions'), ('jobs', 'Jobs')], max_length=100, null=True),
        ),
    ]
