# Generated by Django 5.0.2 on 2024-04-05 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_news_publishing_status_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='publishing_status',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 9, 0, 56, 716328, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
