# Generated by Django 5.0.2 on 2024-04-05 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_advertisement_publishing_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 5, 9, 1, 29, 643288, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
