# Generated by Django 5.0.2 on 2024-04-07 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('Insection_ad', 'InSection_ad'), ('Top', 'Top'), ('Sidebar', 'Sidebar')], max_length=50),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 7, 40, 7, 948543, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
