# Generated by Django 5.0.2 on 2024-04-07 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 7, 19, 58, 45, 279833, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
