# Generated by Django 5.0.2 on 2024-04-08 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_news_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 8, 9, 52, 8, 429636, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
