# Generated by Django 5.0.2 on 2024-04-12 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='relavant_topics',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 14, 52, 18, 894683, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
