# Generated by Django 5.0.2 on 2024-04-15 09:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_news_relavant_topics_alter_news_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='written_by',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 9, 50, 36, 618723, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='relavant_topics',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
